// Example of a constant
export const FETCH_GIF_DATA = 'weirdnessCalculator/NewPage/FETCH_GIF_DATA';
export const ON_DATA_FECTCH_START = 'weirdnessCalculator/NewPage/ON_DATA_FECTCH_START';
export const ON_DATA_FECTCH_SUCESS = 'weirdnessCalculator/NewPage/ON_DATA_FECTCH_SUCESS';
export const ON_DATA_FECTCH_FAILED = 'weirdnessCalculator/NewPage/ON_DATA_FECTCH_FAILED';
export const ON_DATA_FECTCH_DONE = 'weirdnessCalculator/NewPage/ON_DATA_FECTCH_DONE';
export const DELETE_LIKED_GIF = 'weirdnessCalculator/NewPage/DELETE_LIKED_GIF';
export const ADD_LIKED_GIF = 'weirdnessCalculator/NewPage/ADD_LIKED_GIF';
export const CLEAR_GIF_DATA = 'weirdnessCalculator/NewPage/CLEAR_GIF_DATA';
export const ON_START_OVER = 'weirdnessCalculator/NewPage/ON_START_OVER';
